"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# 비밀키는 저장소에 두지 않는다. .env 는 gitignore 되어 있고, .env.example 이 형식을 알려준다.
# 기본값은 로컬 개발 전용이며, 운영에서는 .env 가 없으면 뜨지 않게 아래에서 막는다.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-only-insecure-key')

DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

if not DEBUG and SECRET_KEY == 'dev-only-insecure-key':
    raise RuntimeError('운영 모드인데 DJANGO_SECRET_KEY 가 설정되지 않았다.')

# 쉼표로 구분해 .env 에 넣는다. 예: ALLOWED_HOSTS=api.highfive.app,localhost
#
# .env 에 `ALLOWED_HOSTS=` 처럼 빈 값으로 적혀 있으면 getenv 의 기본값이 먹지 않는다.
# 그래서 값이 비어 있으면 없는 것으로 보고, 개발 중에는 전부 허용한다.
_allowed = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
ALLOWED_HOSTS = _allowed or (['*'] if DEBUG else [])

if not DEBUG and not ALLOWED_HOSTS:
    raise RuntimeError('운영 모드인데 ALLOWED_HOSTS 가 비어 있다.')


# Application definition

INSTALLED_APPS = [
    # ⚠️ django.contrib.* 보다 **앞에** 둔다.
    # Django 는 INSTALLED_APPS 를 뒤에서부터 훑으며 관리 명령을 등록해서, 앞에 있는 앱이
    # 이긴다. 뒤에 두면 staticfiles 의 runserver 가 우리 것을 덮어쓴다.
    'user_manager',
    'workout_manager',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    # refresh 토큰 회전 시 쓴 토큰을 무효화하려면 이 앱이 필요하다(테이블을 만든다).
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CommonMiddleware 보다 앞에 있어야 한다.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'highfive'),
        'USER': os.getenv('DB_USER', 'highfive'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'highfive-local-password'),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

# 저장은 UTC 로 통일한다. 앱도 UTC 로 보내므로 서버에서 시간대를 섞지 않는다.
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# 운동 경로·심박 원본 파일 저장소. 로컬에서는 값이 없으면 파일시스템을 사용하고,
# MinIO/S3 환경 변수를 넣으면 코드 변경 없이 비공개 객체 저장소로 전환된다.
MEDIA_ROOT = BASE_DIR / '.local-media'
MEDIA_URL = '/media/'
S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME', '').strip()
S3_ACCESS_KEY = os.getenv('S3_ACCESS_KEY')
S3_SECRET_KEY = os.getenv('S3_SECRET_KEY')
S3_ENDPOINT_URL = os.getenv('S3_ENDPOINT_URL') or None
S3_PUBLIC_ENDPOINT_URL = os.getenv('S3_PUBLIC_ENDPOINT_URL') or None
S3_REGION = os.getenv('S3_REGION', 'ap-northeast-2')
S3_DOWNLOAD_EXPIRES_SECONDS = 300
if S3_BUCKET_NAME:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': S3_BUCKET_NAME,
                'access_key': S3_ACCESS_KEY,
                'secret_key': S3_SECRET_KEY,
                'endpoint_url': S3_ENDPOINT_URL,
                'region_name': S3_REGION,
                'default_acl': None,
                'querystring_auth': True,
                'querystring_expire': S3_DOWNLOAD_EXPIRES_SECONDS,
                'file_overwrite': False,
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

# multipart 전체를 메모리에 무제한 올리지 않는다.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('WORKOUT_UPLOAD_MAX_BYTES', 25 * 1024 * 1024))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 운동별 하이파이브 요약만 저장한다. 원본 관계는 PostgreSQL이 보관한다.
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
    }
}
if 'test' in sys.argv:
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'highfive-tests',
    }


# ─────────────────────────────────────────────────────────────────────────────
# Django REST Framework
# ─────────────────────────────────────────────────────────────────────────────

REST_FRAMEWORK = {
    # 인증은 JWT 하나로만 받는다. 세션 인증을 같이 켜면 브라우저 쿠키로도 API 가
    # 통과해 CSRF 를 신경 써야 하는데, 앱 전용 서버라 그럴 이유가 없다.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 기본을 '로그인 필요'로 둔다. 공개 API 는 뷰에서 AllowAny 를 명시한다.
    # 반대로 두면 인증을 빠뜨린 뷰가 조용히 열린 채로 배포된다.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    # 프레임워크가 내는 오류(인증 실패 등)도 뷰와 같은 `{'s': False, 'msg': ...}` 형태로
    # 맞춘다. 안 맞추면 앱이 오류 형식 두 가지를 다뤄야 한다.
    'EXCEPTION_HANDLER': 'config.api.exception_handler',
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}

# 디버그일 때만 브라우저에서 API 를 눌러볼 수 있게 한다.
if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] += (
        'rest_framework.renderers.BrowsableAPIRenderer',
    )


# ─────────────────────────────────────────────────────────────────────────────
# JWT
# ─────────────────────────────────────────────────────────────────────────────
#
# 열품타는 access 토큰 수명을 36,500일(100년)로 두고 refresh 를 쓰지 않는다.
# 자동 로그인은 되지만 토큰이 유출돼도 무효화할 방법이 없다. 여기서는 표준 방식
# (짧은 access + 긴 refresh + 회전 + 블랙리스트)으로 간다. 앱은 refresh 를 안전한
# 저장소에 두고 access 가 만료되면 갱신한다.

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=90),

    # 갱신할 때마다 refresh 도 새로 발급하고, 쓴 것은 블랙리스트로 보낸다.
    # 탈취된 refresh 가 한 번 쓰이면 그 뒤로는 막힌다.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': SECRET_KEY,
}


# ─────────────────────────────────────────────────────────────────────────────
# CORS
# ─────────────────────────────────────────────────────────────────────────────
#
# 앱(네이티브)은 CORS 대상이 아니다. 관리 화면이나 웹 클라이언트가 생길 때를
# 대비한 설정이며, 그때 .env 에 출처를 넣는다.

CORS_ALLOWED_ORIGINS = [
    o for o in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if o
]
CORS_ALLOW_CREDENTIALS = False


# ─────────────────────────────────────────────────────────────────────────────
# Firebase
# ─────────────────────────────────────────────────────────────────────────────
#
# 앱은 Firebase Auth 로 구글·애플 로그인을 하고, 서버는 그 ID 토큰을 검증한다.
# 서비스 계정 키(JSON)는 관리자 권한을 가진 비밀 파일이라 저장소에 넣지 않는다.
# Firebase 콘솔 → 프로젝트 설정 → 서비스 계정에서 내려받아 경로만 .env 에 적는다.

_firebase = os.getenv('FIREBASE_CREDENTIALS', '').strip()
FIREBASE_CREDENTIALS = (BASE_DIR / _firebase) if _firebase else None

if not DEBUG and FIREBASE_CREDENTIALS is None:
    raise RuntimeError('운영 모드인데 FIREBASE_CREDENTIALS 가 설정되지 않았다.')
