# Generated by Django 5.2.17 on 2026-08-25 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('nicknameKey', models.CharField(blank=True, default=None, max_length=20, null=True, unique=True)),
                ('loginProvider', models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], db_index=True, max_length=10)),
                ('deviceType', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android')], db_index=True, default='', max_length=10)),
                ('deviceModel', models.CharField(blank=True, default='', max_length=100)),
                ('osVersion', models.CharField(blank=True, default='', max_length=20)),
                ('appVersion', models.CharField(blank=True, default='', max_length=20)),
                ('timezone', models.CharField(blank=True, default='', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lastLoginAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['loginProvider', 'createdAt'], name='user_manage_loginPr_02e148_idx')],
            },
        ),
    ]
