# Generated by Django 5.2.17 on 2026-08-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcmToken',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
