# Generated by Django 5.2.17 on 2026-08-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_profile_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nicknameKey',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=12, null=True),
        ),
    ]
