# Generated by Django 5.2.17 on 2026-08-31 03:39

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialIndexVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexType', models.CharField(max_length=30)),
                ('algorithmVersion', models.PositiveSmallIntegerField()),
                ('parameters', models.JSONField(default=dict)),
                ('isActive', models.BooleanField(db_index=True, default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('indexType', 'algorithmVersion'), name='unique_spatial_index_algorithm_version'), models.UniqueConstraint(condition=models.Q(('isActive', True)), fields=('isActive',), name='unique_active_spatial_index_version')],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('sourceName', models.CharField(max_length=255)),
                ('sourceWorkoutId', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=30)),
                ('rawType', models.CharField(blank=True, default='', max_length=100)),
                ('startAt', models.DateTimeField(db_index=True)),
                ('endAt', models.DateTimeField()),
                ('distanceMeters', models.FloatField(blank=True, null=True)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('heartRateAvg', models.IntegerField(blank=True, null=True)),
                ('heartRateMin', models.IntegerField(blank=True, null=True)),
                ('heartRateMax', models.IntegerField(blank=True, null=True)),
                ('heartRateSampleCount', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('flightsClimbed', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True)),
                ('deletedAt', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrajectorySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('cellId', models.CharField(max_length=32)),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('indexVersion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajectorySegments', to='workout_manager.spatialindexversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectorySegments', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectorySegments', to='workout_manager.workout')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeObjectKey', models.CharField(blank=True, max_length=700, null=True, unique=True)),
                ('routeContentHash', models.CharField(blank=True, default='', max_length=64)),
                ('routeFileSize', models.PositiveBigIntegerField(default=0)),
                ('heartRateObjectKey', models.CharField(blank=True, max_length=700, null=True, unique=True)),
                ('heartRateContentHash', models.CharField(blank=True, default='', max_length=64)),
                ('heartRateFileSize', models.PositiveBigIntegerField(default=0)),
                ('contentHash', models.CharField(max_length=64)),
                ('formatVersion', models.PositiveSmallIntegerField(default=1)),
                ('routePointCount', models.PositiveIntegerField(default=0)),
                ('heartRateSampleCount', models.PositiveIntegerField(default=0)),
                ('fileSize', models.PositiveBigIntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='workout_manager.workout')),
            ],
        ),
        migrations.CreateModel(
            name='HighFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3Cell', models.CharField(max_length=32)),
                ('overlapStartedAt', models.DateTimeField()),
                ('overlapEndedAt', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('indexVersion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='highFives', to='workout_manager.spatialindexversion')),
                ('segmentA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highFivesAsA', to='workout_manager.trajectorysegment')),
                ('segmentB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highFivesAsB', to='workout_manager.trajectorysegment')),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highFivesAsA', to=settings.AUTH_USER_MODEL)),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highFivesAsB', to=settings.AUTH_USER_MODEL)),
                ('workoutA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highFivesAsA', to='workout_manager.workout')),
                ('workoutB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highFivesAsB', to='workout_manager.workout')),
            ],
            options={
                'indexes': [models.Index(fields=['workoutA', 'indexVersion'], name='workout_man_workout_d86941_idx'), models.Index(fields=['workoutB', 'indexVersion'], name='workout_man_workout_d3400c_idx')],
                'constraints': [models.UniqueConstraint(fields=('workoutA', 'workoutB', 'indexVersion'), name='unique_workout_pair_high_five'), models.CheckConstraint(condition=models.Q(('workoutA__lt', models.F('workoutB'))), name='high_five_ordered_workout_pair'), models.CheckConstraint(condition=models.Q(('overlapStartedAt__lt', models.F('overlapEndedAt'))), name='high_five_positive_overlap')],
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'updatedAt', 'id'], name='workout_man_user_id_96ec45_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'startAt'], name='workout_man_user_id_daa384_idx'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('user', 'source', 'sourceName', 'sourceWorkoutId'), name='unique_user_source_workout'),
        ),
        migrations.AddIndex(
            model_name='trajectorysegment',
            index=models.Index(fields=['workout', 'indexVersion', 'sequence'], name='workout_man_workout_22dded_idx'),
        ),
        migrations.AddIndex(
            model_name='trajectorysegment',
            index=models.Index(fields=['indexVersion', 'cellId'], name='workout_man_indexVe_22f44d_idx'),
        ),
        migrations.AddConstraint(
            model_name='trajectorysegment',
            constraint=models.UniqueConstraint(fields=('workout', 'indexVersion', 'sequence'), name='unique_workout_index_segment_sequence'),
        ),
    ]
