# Generated by Django 5.2.17 on 2026-08-28 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('sourceName', models.CharField(max_length=255)),
                ('sourceWorkoutId', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=30)),
                ('rawType', models.CharField(blank=True, default='', max_length=100)),
                ('startAt', models.DateTimeField(db_index=True)),
                ('endAt', models.DateTimeField()),
                ('distanceMeters', models.FloatField(blank=True, null=True)),
                ('kcal', models.IntegerField(blank=True, null=True)),
                ('heartRateAvg', models.IntegerField(blank=True, null=True)),
                ('heartRateMin', models.IntegerField(blank=True, null=True)),
                ('heartRateMax', models.IntegerField(blank=True, null=True)),
                ('heartRateSampleCount', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('flightsClimbed', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True)),
                ('deletedAt', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'updatedAt', 'id'], name='workout_man_user_id_96ec45_idx'), models.Index(fields=['user', 'startAt'], name='workout_man_user_id_daa384_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'sourceName', 'sourceWorkoutId'), name='unique_user_source_workout')],
            },
        ),
    ]
